# Generated by Django 6.0.1 on 2026-02-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('guide', 'Руководство'), ('error', 'Ошибка')], max_length=10, verbose_name='Тип подсказки')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='equipment.equipment', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HintElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Картинка'), ('video', 'Видео')], max_length=10, verbose_name='Тип элемента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текстовое содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hint_images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='equipment.hint', verbose_name='Подсказка')),
            ],
            options={
                'verbose_name': 'Элемент подсказки',
                'verbose_name_plural': 'Элементы подсказки',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
