# Generated by Django 6.0.1 on 2026-02-10 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_hint_hintelement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название ТО')),
                ('type', models.CharField(choices=[('daily', 'Ежедневное'), ('weekly', 'Еженедельное'), ('monthly', 'Ежемесячное'), ('one_time', 'Одноразовое')], max_length=20, verbose_name='Тип периодичности')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Запланированная дата (для одноразового)')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели (для еженедельного)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='День месяца (для ежемесячного)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='equipment.equipment', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'План ТО',
                'verbose_name_plural': 'Планы ТО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(verbose_name='Запланированная дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('due', 'Необходимо выполнить'), ('in_progress', 'В процессе'), ('done', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_instances', to='equipment.equipment', verbose_name='Техника')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='maintenance.maintenanceplan', verbose_name='План ТО')),
            ],
            options={
                'verbose_name': 'Инстанс ТО',
                'verbose_name_plural': 'Инстансы ТО',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.maintenanceplan', verbose_name='План ТО')),
            ],
            options={
                'verbose_name': 'Шаблон задачи ТО',
                'verbose_name_plural': 'Шаблоны задач ТО',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнена'), ('skipped', 'Пропущена')], default='pending', max_length=20, verbose_name='Статус')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_maintenance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to='maintenance.maintenanceinstance', verbose_name='Инстанс ТО')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancetasktemplate', verbose_name='Шаблон задачи')),
            ],
            options={
                'verbose_name': 'Задача инстанса ТО',
                'verbose_name_plural': 'Задачи инстанса ТО',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='maintenance_photos/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenanceinstance', verbose_name='Инстанс ТО')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_maintenance_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото ТО',
                'verbose_name_plural': 'Фото ТО',
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['instance'], name='maintenance_instanc_eb07d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['equipment', 'type', 'is_active'], name='maintenance_equipme_8e3059_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['is_active', 'type'], name='maintenance_is_acti_7bac1c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceinstance',
            index=models.Index(fields=['scheduled_date', 'status'], name='maintenance_schedul_e403a6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceinstance',
            index=models.Index(fields=['equipment', 'scheduled_date'], name='maintenance_equipme_7372f2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceinstance',
            index=models.Index(fields=['plan', 'scheduled_date'], name='maintenance_plan_id_6eac31_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceinstance',
            index=models.Index(fields=['status'], name='maintenance_status_b07d5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceinstance',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_date'), name='unique_maintenance_instance'),
        ),
        migrations.AddIndex(
            model_name='maintenancetasktemplate',
            index=models.Index(fields=['plan', 'order'], name='maintenance_plan_id_dc7250_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetaskinstance',
            index=models.Index(fields=['instance', 'status'], name='maintenance_instanc_2fc0bd_idx'),
        ),
    ]
