# Generated by Django 6.0.1 on 2026-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenancetaskinstance',
            name='maintenance_instanc_2fc0bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancetasktemplate',
            name='maintenance_plan_id_dc7250_idx',
        ),
        migrations.AddField(
            model_name='maintenanceinstance',
            name='task_states',
            field=models.JSONField(default=list, help_text='[{"title": "...", "is_required": true, "status": "pending", "checked_by_id": null, "checked_at": null, "comment": ""}]', verbose_name='Состояние задач'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='tasks',
            field=models.JSONField(default=list, help_text='Список задач: [{"title": "...", "is_required": true, "order": 0}]', verbose_name='Задачи'),
        ),
        migrations.RemoveField(
            model_name='maintenancetasktemplate',
            name='plan',
        ),
        migrations.DeleteModel(
            name='MaintenanceTaskInstance',
        ),
        migrations.DeleteModel(
            name='MaintenanceTaskTemplate',
        ),
    ]
