# Generated by Django 6.0.1 on 2026-02-10 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenancetaskinstance_maintenance_instanc_2fc0bd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='maintenanceinstance',
            name='task_states',
            field=models.JSONField(default=list, help_text='[{"title": "...", "is_required": true, "status": "pending", ...}]', verbose_name='Состояние задач'),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.maintenanceplan', verbose_name='План ТО')),
            ],
            options={
                'verbose_name': 'Задача ТО',
                'verbose_name_plural': 'Задачи ТО',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['plan', 'order'], name='maintenance_plan_id_87cb95_idx')],
            },
        ),
    ]
