# Generated by Django 6.0.1 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenanceinstance_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='generate_first_instance',
            field=models.BooleanField(default=False, help_text='Создать первый инстанс ТО сразу при сохранении плана', verbose_name='Создать инстанс сейчас'),
        ),
    ]
