# Generated by Django 6.0.1 on 2026-02-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Картинка'), ('video', 'Видео')], max_length=10, verbose_name='Тип элемента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification_images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Элемент уведомления',
                'verbose_name_plural': 'Элементы уведомления',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
